"""Walk-forward analysis with out-of-sample (OOS) stitching.

The honest test of whether an edge holds up. We never optimize once over all
history. Instead we roll a window forward:

    [---- train ----][- test -]
            [---- train ----][- test -]
                    [---- train ----][- test -]

For each fold we pick the best parameter on the IN-SAMPLE (train) window, then
evaluate that choice on the immediately following OUT-OF-SAMPLE (test) window.
The test segments are concatenated into one OOS equity curve — that stitched
curve is the realistic estimate, because every point in it was generated by a
parameter chosen WITHOUT seeing that data.

We also report the parameter selected in each fold: if it jumps around wildly,
the "edge" is probably noise (overfitting).
"""
from __future__ import annotations

from dataclasses import dataclass, field, replace
from typing import Callable, Dict, List, Optional

import pandas as pd

from ..config import BacktestConfig, RiskPolicy
from .engine import run_backtest
from .metrics import compute_metrics


@dataclass
class Fold:
    train_start: str
    train_end: str
    test_start: str
    test_end: str
    best_param: dict
    train_score: float
    oos_metrics: Dict[str, float]


@dataclass
class WalkForwardResult:
    oos_equity: pd.Series
    oos_metrics: Dict[str, float]
    folds: List[Fold] = field(default_factory=list)
    benchmark_equity: Optional[pd.Series] = None
    benchmark_metrics: Dict[str, float] = field(default_factory=dict)
    select_by: str = "sharpe"


def walk_forward(
    history: Dict[str, pd.DataFrame],
    strategy_factory: Callable[..., object],
    param_grid: List[dict],
    policy: RiskPolicy,
    base_cfg: BacktestConfig,
    train_years: int = 3,
    test_years: int = 1,
    step_years: int = 1,
    select_by: str = "sharpe",
) -> WalkForwardResult:
    if not param_grid:
        raise ValueError("param_grid is empty.")

    all_dates = sorted(set().union(*[set(df.index) for df in history.values()]))
    if base_cfg.start:
        all_dates = [d for d in all_dates if d >= pd.to_datetime(base_cfg.start)]
    if base_cfg.end:
        all_dates = [d for d in all_dates if d <= pd.to_datetime(base_cfg.end)]
    if not all_dates:
        raise ValueError("No dates in range.")
    first, last = all_dates[0], all_dates[-1]

    folds: List[Fold] = []
    oos_segments: List[pd.Series] = []

    train_start = first
    while True:
        train_end = train_start + pd.DateOffset(years=train_years)
        test_start = train_end
        test_end = min(test_start + pd.DateOffset(years=test_years), last)
        if test_start >= last:
            break

        # --- select best parameter on the training (in-sample) window ---
        best_param, best_score = None, float("-inf")
        for params in param_grid:
            cfg_tr = replace(base_cfg, start=str(train_start.date()),
                             end=str(train_end.date()))
            try:
                res = run_backtest(history, strategy_factory(**params), policy, cfg_tr)
            except ValueError:
                continue
            score = res.metrics.get(select_by, float("-inf"))
            if score is not None and score > best_score:
                best_score, best_param = score, params
        if best_param is None:
            train_start = train_start + pd.DateOffset(years=step_years)
            continue

        # --- evaluate that choice on the OOS (test) window --------------
        cfg_te = replace(base_cfg, start=str(test_start.date()),
                         end=str(test_end.date()))
        oos = run_backtest(history, strategy_factory(**best_param), policy, cfg_te)
        oos_ret = oos.equity.pct_change().dropna()
        if len(oos_ret):
            oos_segments.append(oos_ret)
        folds.append(
            Fold(
                train_start=str(train_start.date()), train_end=str(train_end.date()),
                test_start=str(test_start.date()), test_end=str(test_end.date()),
                best_param=best_param, train_score=round(best_score, 3),
                oos_metrics=oos.metrics,
            )
        )
        train_start = train_start + pd.DateOffset(years=step_years)

    if not oos_segments:
        raise ValueError("No OOS folds produced — widen the date range or windows.")

    # stitch OOS returns into one compounded equity curve
    stitched = pd.concat(oos_segments).sort_index()
    stitched = stitched[~stitched.index.duplicated(keep="first")]
    oos_equity = (1.0 + stitched).cumprod() * base_cfg.initial_cash
    oos_metrics = compute_metrics(oos_equity)

    bench_equity, bench_metrics = None, {}
    bdf = history.get(base_cfg.benchmark)
    if bdf is not None:
        bclose = bdf["close"].reindex(oos_equity.index).ffill().dropna()
        if len(bclose) > 1:
            bench_equity = (bclose / bclose.iloc[0]) * base_cfg.initial_cash
            bench_metrics = compute_metrics(bench_equity)

    return WalkForwardResult(
        oos_equity=oos_equity, oos_metrics=oos_metrics, folds=folds,
        benchmark_equity=bench_equity, benchmark_metrics=bench_metrics,
        select_by=select_by,
    )
